apiVersion: v1
data:
  client-passwords: UTdvMUszc0FyWA==
  controller-password: SlcxM3dvS1pnNQ==
  inter-broker-password: VzZFOE1HUFZESQ==
  system-user-password: UTdvMUszc0FyWA==
kind: Secret
metadata:
  name: kafka-user-passwords
  namespace: or
type: Opaque
