apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "live-job.fullname" . }}-live
  labels:
    {{- include "live-job.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.live.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.live.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
        - name: my-container
          image: {{ .Values.live.image.repository }}:{{ .Values.live.image.tag | default .Chart.AppVersion }}
          env:
            - name: DISCORD_URL
              value: {{ quote .Values.env.discordUrl }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SASL_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.env.kafkaSASL.key }}
                  name: {{ .Values.env.kafkaSASL.name }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - configMapRef:
                name: app-env
          resources: {}
      restartPolicy: Never
