apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.frontend.name }}
  name: {{ include "scraping-app.fullname" . }}-service
spec:
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.frontend.name }}
  type: {{ .Values.service.type }}
